name: Deploy client source to deployment branch

on:
  push:
    branches:
      - main

jobs:
  deploy-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Install Rollup
        run: npm install -g rollup

      - name: Build
        run: |
          npm install 
          cd packages/ui
          rollup -c
          cd ../../

      - name: Deploy public/ to frontend_deploy
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/smtdfc/aurora.git
          git fetch origin frontend_deploy

          # Add the deployment branch as a worktree
          git worktree add deployment-dir frontend_deploy

          # Clean old deployment files
          rm -rf deployment-dir/*

          # Copy built files to deployment dir
          rsync -av --exclude='.git' --delete ./public/ deployment-dir/

          cd deployment-dir

          # Stage and commit changes if any
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Deploy client from main at $(date)"
            git push origin HEAD:frontend_deploy
          else
            echo "No changes to deploy"
          fi

          # Cleanup worktree
          cd ..
          git worktree remove deployment-dir