name: Deploy client source to deployment branch

on:
  push:
    branches:
      - main

jobs:
  deploy-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Install Rollup
        run: npm install -g rollup

      - name: Build
        run: |
          npm install 
          cd packages/ui
          rollup -c
          cd ../../
          
      - name: Deploy source code to deployment branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/smtdfc/aurora.git
          git pull origin frontend_deploy --rebase

          # Add the deployment branch as a worktree
          git worktree add deployment-dir frontend_deploy
          
          # Sync the built files to the deployment directory
          rsync -av --delete \
            --exclude='.git' \
            --exclude='packages' \
            --exclude='node_modules' \
            --exclude='deployment-dir' \
            --exclude='.github' \
            ./public/

          # Stage and commit changes if any
          git add .
          git commit -m "Deploy client from main at $(date)" || echo "No changes to commit"

          # Push changes to the frontend_deploy branch
          git push origin HEAD:frontend_deploy