name: Deploy server source to deployment branch

on:
  push:
    branches:
      - main

jobs:
  deploy-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Deploy source code to deployment branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/smtdfc/aurora.git

          git fetch origin backend_deploy
          git worktree add deployment-dir backend_deploy

          rsync -av --delete --exclude='packages/ui' --exclude='public' --exclude='node_modules' ./ deployment-dir/

          cd deployment-dir
          git add .
          git commit -m "Deploy server source from main at $(date)" || echo "Nothing to commit"
          git push origin HEAD:backend_deploy